[id]
  languageName = "Indonesian"
  contentDir = "content/id"
  weight = 10
  [id.params]
    languageISO = "ID"
    languageTag = "id-ID"
    footer = '<svg  xmlns="http://www.w3.org/2000/svg"  width="24"  height="24"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"  class="icon icon-tabler icons-tabler-outline icon-tabler-umbrella"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M4 12a8 8 0 0 1 16 0z" /><path d="M12 12v6a2 2 0 0 0 4 0" /></svg> <a class="text-muted" href="https://gohugo.com/">Hugo</a> & <a class="text-muted" href="https://getdoks.org/">Doks</a>'
    alertText = '<a class="alert-link stretched-link fw-normal" href="/blog/example-post/">Doks versi 1.0 telah dirilis!</a>'

[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 15
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    footer = '<svg  xmlns="http://www.w3.org/2000/svg"  width="24"  height="24"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"  class="icon icon-tabler icons-tabler-outline icon-tabler-umbrella"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M4 12a8 8 0 0 1 16 0z" /><path d="M12 12v6a2 2 0 0 0 4 0" /></svg> <a class="text-muted" href="https://gohugo.com/">Hugo</a> & <a class="text-muted" href="https://getdoks.org/">Doks</a>'
    alertText = '<a class="alert-link stretched-link fw-normal" href="/blog/example-post/">Doks version 1.0 just shipped!</a>'

[de]
  languageName = "German"
  contentDir = "content/de"
  weight = 20
  [de.params]
    languageISO = "DE"
    languageTag = "de-DE"
    footer = 'Gebaut mit <a class="text-muted" href="https://gethyas.com/">Hyas</a>'
    alertText = 'Neue Version ist da! <a class="alert-link stretched-link" href="https://getdoks.org/blog/doks-v0.5/">Doks v0.5</a>'

[nl]
  languageName = "Nederlands"
  contentDir = "content/nl"
  weight = 25
  [nl.params]
    languageISO = "NL"
    languageTag = "nl-NL"
    titleAddition = "Modern documentatie-thema"
    description = "Doks is een Hugo-thema waarmee je moderne documentatie-websites kunt bouwen die veilig, snel en klaar voor SEO zijn — standaard."
    titleHome = "Doks thema"
    footer = 'Mogelijk gemaakt door <a href="https://www.netlify.com/">Netlify</a>, <a href="https://gohugo.io/">Hugo</a>, en <a href="https://getdoks.org/">Doks</a>'
    alertText = 'Introductie van het Doks-kinderthema, verschillende DX + UX-updates en meer! <a class="alert-link stretched-link" href="https://getdoks.org/blog/doks-v0.2/">Bekijk Doks v0.2</a>'
